name: read_me
description: A new Flutter project.
version: 1.0.1+1
publish_to: none
environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  alice: 0.4.1
  cached_network_image: null
  carousel_slider: null
  copy_with_extension: null
  crypto: ^3.0.3
  cupertino_icons: null
  curl_logger_dio_interceptor: null
  dartz: null
  device_info_plus: ^9.1.2
  dio: ^5.1.2
  dio_cache_interceptor: null
  dio_cache_interceptor_hive_store: null
  encrypt: null
  equatable: null
  file_picker: ^8.0.3
  firebase_analytics: ^10.10.7
  firebase_core: null
  firebase_crashlytics: null
  firebase_messaging: null
  firebase_remote_config: ^4.3.8
  flutter:
    sdk: flutter
  flutter_background_executor: ^1.0.0
  flutter_dotenv: null
  flutter_form_builder: null
  flutter_hooks: ^0.20.3
  flutter_html: 3.0.0-beta.2
  flutter_image_compress: null
  flutter_local_notifications: ^16.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.7
  form_builder_validators: null
  freezed_annotation: null
  get: null
  hive: null
  hive_flutter: null
  image: ^4.1.7
  image_picker: null
  intl: null
  json_annotation: null
  lucide_icons: null
  open_filex: ^4.4.0
  package_info_plus: ^4.2.0
  path: ^1.8.0
  permission_handler: ^11.0.1
  pretty_dio_logger: null
  retrofit: null
  screenshot: null
  shared_preferences: ^2.2.2
  sizer: 2.0.15
  skeletonizer: null
  unicons: ^2.1.1
  url_launcher: ^6.0.20
  video_player: ^2.8.7
  webview_flutter: ^4.4.2
  just_audio: ^0.9.38
  syncfusion_flutter_charts: 24.2.3
  device_preview: ^1.1.0
  month_picker_dialog: 

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.0.4
  husky: ^0.1.6
  json_serializable: ^6.3.1
  retrofit_generator: null
  mockito: ^5.0.8
  

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - environments/
    # - shorebird.yaml
